language: node_js
node_js:
  - 4
  - 6
cache:
  directories:
    - node_modules
   
install:
  - npm install -g codecov    
script:
  - npm test -- --coverage
  - codecov
  
after_success:
  - bash <(curl -s https://codecov.io/bash)  